// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Attributes struct {
	ID    string `json:"id"`
	Value string `json:"value"`
}

type ChangePasswordInput struct {
	ID       string `json:"id"`
	Password string `json:"password"`
}

type CreateItemInput struct {
	TypeID   string  `json:"typeId"`
	Lon      float64 `json:"lon"`
	Lat      float64 `json:"lat"`
	BrokenID *string `json:"brokenId"`
}

type CreateRentInput struct {
	ExternalID string `json:"externalId"`
	ItemsID    string `json:"itemsId"`
}

type CreateUserInput struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Password  string `json:"password"`
	RolesID   string `json:"rolesId"`
}

type InputList struct {
	Name       string        `json:"name"`
	Attributes []*Attributes `json:"attributes"`
}

type InputTypes struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Title string `json:"title"`
}

type LocationGenInput struct {
	LonMin float64 `json:"lonMin"`
	LonMax float64 `json:"lonMax"`
	LatMin float64 `json:"latMin"`
	LatMax float64 `json:"latMax"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Permissions struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

type Role struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Desc  string `json:"desc"`
}

type RolesPermissions struct {
	RolesID       string `json:"rolesId"`
	PermissionsID string `json:"permissionsId"`
}

type TypeNames struct {
	Name string `json:"name"`
}

type UpdateAdminInput struct {
	ID        string  `json:"id"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	RolesID   string  `json:"rolesId"`
}

type UpdateItemInput struct {
	ID       string   `json:"id"`
	TypeID   *string  `json:"typeId"`
	Lon      *float64 `json:"lon"`
	Lat      *float64 `json:"lat"`
	BrokenID *string  `json:"brokenId"`
}

type UpdateUserInput struct {
	ID        string  `json:"id"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
}

type UserSettings struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
